version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    labels:
      - "dependencies"
    groups:
      docker:
        patterns:
          - "*"
