owner: aicage

ignore_repos: []

dependabot:
  profiles:
    actions-only: ./config/dependabot/actions-only.yml
    npm-actions: ./config/dependabot/npm-actions.yml
    pip-actions: ./config/dependabot/pip-actions.yml
    pip-docker-actions: ./config/dependabot/pip-docker-actions.yml
  repos:
    aicage: pip-actions
    aicage-custom-samples: actions-only
    aicage-image: pip-docker-actions
    aicage-image-base: pip-docker-actions
    aicage-image-util: pip-docker-actions
    demo-repository: npm-actions

rules:
  - selector:
      all: true
      fork: false
    settings: {}

  - selector:
      repos:
        - aicage-custom-samples
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/actions-only.yml

  - selector:
      repos:
        - demo-repository
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/npm-actions.yml

  - selector:
      repos:
        - aicage
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/pip-actions.yml

  - selector:
      repos:
        - aicage-image
        - aicage-image-base
        - aicage-image-util
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/pip-docker-actions.yml
