owner: bats-hardened

ignore_repos: []

dependabot:
  profiles:
    .github: ./config/dependabot/bats-hardened/.github/dependabot.yml
    bats-action: ./config/dependabot/bats-hardened/bats-action/dependabot.yml
    bats-assert: ./config/dependabot/bats-hardened/bats-assert/dependabot.yml
    bats-core: ./config/dependabot/bats-hardened/bats-core/dependabot.yml
    bats-detik: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml
    bats-file: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml
    bats-support: ./config/dependabot/bats-hardened/bats-support/dependabot.yml
  repos:
    .github: .github
    bats-action: bats-action
    bats-assert: bats-assert
    bats-core: bats-core
    bats-detik: bats-detik
    bats-support: bats-support

rules:
  - selector:
      all: true
      fork: true
    settings:
      rulesets-file: ./config/rulesets/commits-must-be-signed.json

  - selector:
      repos:
        - .github
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/.github/dependabot.yml

  - selector:
      repos:
        - bats-action
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-action/dependabot.yml

  - selector:
      repos:
        - bats-assert
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-assert/dependabot.yml

  - selector:
      repos:
        - bats-core
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-core/dependabot.yml

  - selector:
      repos:
        - bats-detik
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml

  - selector:
      repos:
        - bats-file
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-file/dependabot.yml

  - selector:
      repos:
        - bats-support
      fork: true
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-support/dependabot.yml
