owner: bats-hardened

ignore_repos: []

dependabot:
  profiles:
    .github: ./config/dependabot/bats-hardened/.github/dependabot.yml
    bats-action: ./config/dependabot/bats-hardened/bats-action/dependabot.yml
    bats-assert: ./config/dependabot/bats-hardened/bats-assert/dependabot.yml
    bats-core: ./config/dependabot/bats-hardened/bats-core/dependabot.yml
    bats-detik: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml
    bats-file: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml
    bats-support: ./config/dependabot/bats-hardened/bats-support/dependabot.yml
  repos:
    .github: .github
    bats-action: bats-action
    bats-assert: bats-assert
    bats-core: bats-core
    bats-detik: bats-detik
    bats-support: bats-support

rules:
  # - selector:
  #     all: true
  #   settings:
  #     rulesets-file: ./config/rulesets/commits-must-be-signed.json

  - selector:
      repos:
        - .github
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/.github/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/.github/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-action
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-action/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-action/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-assert
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-assert/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-assert/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-core
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-core/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-core/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-detik
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-detik/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-detik/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-file
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-file/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-file/renovate.json
          target: renovate.json

  - selector:
      repos:
        - bats-support
    settings:
      dependabot-yml: ./config/dependabot/bats-hardened/bats-support/dependabot.yml
      file-sync:
        - name: Renovate configuration
          source: ./config/renovate/bats-hardened/bats-support/renovate.json
          target: renovate.json
