owner: gh-workflow

ignore_repos: []

dependabot:
  profiles:
    pip-actions: ./config/dependabot/pip-actions.yml
  repos:
    action-template: pip-actions
    multiarch-image-publish: pip-actions
    setup-docker-desktop-macos: pip-actions

rules:
  - selector:
      all: true
      fork: false
    settings: {}

  - selector:
      repos:
        - action-template
        - multiarch-image-publish
        - setup-docker-desktop-macos
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/pip-actions.yml
