owner: gh-workflow

ignore_repos: []

dependabot:
  profiles:
    actions-only: ./config/dependabot/actions-only.yml
    npm-actions: ./config/dependabot/npm-actions.yml
    pip-actions: ./config/dependabot/pip-actions.yml
  repos:
    action-template: pip-actions
    container-host-user: actions-only
    multiarch-image-publish: pip-actions
    setup-docker-desktop-macos: pip-actions

rules:
  - selector:
      all: true
      fork: false
    settings: {}

  - selector:
      repos:
        - container-host-user
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/actions-only.yml

  - selector:
      repos:
        - action-template
        - multiarch-image-publish
        - setup-docker-desktop-macos
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/pip-actions.yml
