owner: ghcr-manager

ignore_repos: []

dependabot:
  profiles:
    npm-actions: ./config/dependabot/npm-actions.yml
  repos:
    ghcr-cleanup-manager: npm-actions
    ghcr-manager: npm-actions
    ghcr-untag-action: npm-actions

rules:
  - selector:
      all: true
      fork: false
    settings: {}

  - selector:
      repos:
        - ghcr-cleanup-manager
        - ghcr-manager
        - ghcr-untag-action
      fork: false
    settings:
      dependabot-yml: ./config/dependabot/npm-actions.yml
