ignore_repos: []

dependabot:
  profiles:
    none: ./config/dependabot/none.yml
    actions-only: ./config/dependabot/actions-only.yml
    pip-only: ./config/dependabot/pip-only.yml
    pip-actions: ./config/dependabot/pip-actions.yml
    pip-docker-actions: ./config/dependabot/pip-docker-actions.yml
    docker-only: ./config/dependabot/docker-only.yml
    maven-only: ./config/dependabot/maven-only.yml
  repos:
    sync-github-repo-settings: pip-actions
    python-repo-template: pip-actions
    watchpuppy2: pip-actions
    watchpuppy: pip-docker-actions
    mindcraft-demo: docker-only
    routheon: pip-docker-actions
    llm-aggregator: pip-actions
    extract2md: pip-actions
    mcp-base64: actions-only
    llm-structured-output-demo: actions-only
    docker-vpn-bridge: docker-only
    ollama_config: docker-only
    minecraft-server: docker-only
    sot_autofish: pip-only
    time-series-prediction: pip-only
    mc-plugin-playground: maven-only
    adfree-dns-pi-cluster: none
    cfbaker: none
    deterministic-zip: none
    ebuild-test-suite: none
    fastmcp-ollama: none
    gentoo-config: none
    gentoo-overlay: none
    gentoo-raspberrypi-builder: none
    htmltranslationextract: none
    inguma: none
    LeosMessenger: none
    LeosProject: none
    local--usr-local-bin: none
    localrepo: none
    local_overlay: none
    mcp-gitlock: none
    pentoo-iso-tester: none
    schreibg: none
    space-invaders: none
    SQL-Find-Circular-References: none
    tensorflow-quickstart: none
    test: none
    usialtgr: none
    usialtgr-no-capslock: none
    workflow-ready-template: none
