name: Test Suite

"on":
  workflow_call:
  workflow_dispatch:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          ./scripts/lint.sh
